config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'static_pages/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get :signup,       to: 'users#new'
  resources :keywords
  resources :users
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :volume, :goal_pv, :goal_cvr, :goal_price, :goal_profit, :goal_rank, presence: true
  validates :description, length: { maximum: 200 }
  validates :query, presence: true, length: { maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :keywords, dependent: :destroy
  attr_accessor :remember_token
  before_save :downcase_email
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self
    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  private

    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :logged_in_user

  def new
    @keyword = Keyword.new
  end

  def create
    @keyword = current_user.keywords.build(keyword_params)
    if @keyword.save
      flash[:success] = "キーワードが登録されました！"
      redirect_to current_user
    else
      render 'keywords/new'
    end
  end
  
  def edit
    @keyword = Keyword.find(params[:id])
  end

  def update
    @keyword = Keyword.find(params[:id])
    if @keyword.update_attributes(keyword_params)
      flash[:success] = "キーワード情報が更新されました！"
      redirect_to current_user
    else
      render 'edit'
    end
  end
  
  def destroy
    @keyword = Keyword.find(params[:id])
    @keyword.destroy
    flash[:success] = "キーワードが削除されました"
    redirect_back(fallback_location: root_path)
  end

  private

    def keyword_params
      params.require(:keyword).permit(:query, :volume, :goal_rank, :goal_pv,
                                      :goal_cvr, :goal_price, :goal_profit, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'メールアドレスとパスワードの組み合わせが誤っています'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user

  def index
  end

  def show
    @user = User.find(params[:id])
    @keywords = @user.keywords.paginate(page: params[:page], per_page: 20).order(goal_profit: "DESC")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ようこそ！"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params_update)
      flash[:success] = "プロフィールが更新されました！"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  
    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end

    # ユーザー新規作成時に許可する属性
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # プロフィール編集時に許可する属性
    def user_params_update
      params.require(:user).permit(:name, :email, :introduction, :media_url, :total_goal_profit)
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      if !current_user?(@user)
        flash[:danger] = "このページへはアクセスできません"
        redirect_to(root_url)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')  # full_titleメソッドを定義
    base_title = 'Keyword-profit'
    if page_title.blank?
      base_title  # トップページはタイトル「Keyword-profit」
    end
  end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  # ユーザーのセッションを永続的にする
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # 記憶トークンcookieに対応するユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)  # 追記
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80, cl: "gravatar")
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: cl)
  end
end

app/views/keywords/_keyword_form.html.slim
= form_with model: @keyword, local: true do |f|
  = render 'shared/error_messages', object: f.object
  .form-group
    = f.label :キーワード
    = f.text_field :query, class: 'form-control', id: 'keyword_query'
  .form-group
    = f.label :検索ボリューム
    = f.text_field :volume, class: 'form-control', id: 'keyword_volume'
  .form-group
    = f.label :目標順位
    |  (位) 
    = f.text_field :goal_rank, class: 'form-control', id: 'keyword_goal_rank'
  .form-group
    = f.label :想定流入数
    |  (PV) 
    = f.text_field :goal_pv, class: 'form-control', id: 'keyword_goal_pv'
  .form-group
    = f.label :想定CVR
    |  (%) 
    = f.text_field :goal_cvr, class: 'form-control', id: 'keyword_goal_cvr'
  .form-group
    = f.label :平均単価
    |  (円) 
    = f.text_field :goal_price, class: 'form-control', id: 'keyword_goal_price'
  .form-group
    = f.label :想定報酬額
    |  (円) 
    = f.text_field :goal_profit, class: 'form-control', id: 'keyword_goal_profit'
  .form-group
    = f.label :メモ
    = f.text_field :description, size: "60x4", class: 'form-control', id: 'keyword_description'
  = f.submit nil, class: 'btn btn-primary'

app/views/keywords/edit.html.slim
- provide(:title, "キーワード編集")
.container
  h1
    | キーワード編集
  .row
    .col-md-6.col-md-offset-3
      = form_with model: @keyword, local: true do |f|
        = render 'shared/error_messages', object: f.object
        .form-group
          = f.label :キーワード
          = f.text_field :query, class: 'form-control', id: 'keyword_query'
        .form-group
          = f.label :検索ボリューム
          = f.text_field :volume, class: 'form-control', id: 'keyword_volume'
        .form-group
          = f.label :目標順位
          |  (位) 
          = f.text_field :goal_rank, class: 'form-control', id: 'keyword_goal_rank'
        .form-group
          = f.label :想定流入数
          |  (PV) 
          = f.text_field :goal_pv, class: 'form-control', id: 'keyword_goal_pv'
        .form-group
          = f.label :想定CVR
          |  (%) 
          = f.text_field :goal_cvr, class: 'form-control', id: 'keyword_goal_cvr'
        .form-group
          = f.label :平均単価
          |  (円) 
          = f.text_field :goal_price, class: 'form-control', id: 'keyword_goal_price'
        .form-group
          = f.label :想定報酬額
          |  (円) 
          = f.text_field :goal_profit, class: 'form-control', id: 'keyword_goal_profit'
        .form-group
          = f.label :メモ
          = f.text_field :description, size: "60x4", class: 'form-control', id: 'keyword_description'
        = f.submit "更新する", class: "btn btn-primary"

app/views/keywords/new.html.slim
- provide(:title, "キーワード登録")
.container
  h1
    | キーワード登録
  .row
    .col-md-6.col-md-offset-3
      = render 'keywords/keyword_form'

app/views/layouts/_footer.html.slim
footer
  .container
    .row.copyright
      .col-md-12.text-center
        p

  small.block
    | © 2021 Muranaka All Rights Reserved.

app/views/layouts/_header.html.slim
header.navbar.fixed-top
  .container
    nav
      - if logged_in?
        = link_to(image_tag("Keyword-profit.jpg", :alt => ""), current_user, id: 'logo')
        ul.nav.navbar-nav.navbar-right
          li.dropdown

        a.dropdown-toggle[href="#" data-toggle="dropdown"]
          |  アカウント 
        b.caret
        ul.dropdown-menu
          li
            = link_to 'プロフィール', current_user
          li.divider
          li
            = link_to 'ログアウト', logout_path, method: :delete
      - else
        = link_to(image_tag("Keyword-profit.jpg", :alt => ""), root_url, id: 'logo')
        ul.nav.navbar-nav.navbar-right
          li
            = link_to 'ユーザー登録(無料)', signup_path
          li
            = link_to 'ログイン', login_path
          |  </ul 

app/views/layouts/_rails_default.html.slim
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag    'application', media: 'all',
-                            'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = render 'layouts/rails_default'
    = render 'layouts/shim'
  body
    #page
      = render 'layouts/header'
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
      = yield
    = render 'layouts/footer'

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    ul
      - object.errors.full_messages.each do |msg|
        li
          = msg

app/views/static_pages/home.html.slim
center
  h1.top-copy
    | 世界でもっともシンプルなキーワード選定ツール
  li.btn.btn--orange
    = link_to 'ユーザー登録（無料）', "/signup", {class: "btn-link"}

app/views/users/edit.html.slim
- provide(:title, "プロフィール編集")
.row
  .col-md-6.col-md-offset-3
    = form_for(@user) do |f|
      = render 'shared/error_messages', object: f.object
      .gravatar_edit
        = gravatar_for(@user, size: 40)
        = @user.name
      a[href="http://gravatar.com/emails" target="_blank"]
        | プロフィール写真を変更
  p
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'user_name'
  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control', id: 'user_email'
  .form-group
    = f.label :introduction
    = f.text_area :introduction, size: "60x4", class: 'form-control', id: 'user_introduction'
  .form-group
    = f.label "登録サイト"
    = f.text_area :media_url, class: 'form-control', id: 'user_media_url'
  .form-group
    = f.label "目標月額発生金額"
    = f.text_area :total_goal_profit, class: 'form-control', id: 'user_total_goal_profit'
  = f.submit "更新する", class: "btn btn-primary"

app/views/users/index.html.slim
h1
  | Users#index
p
  | Find me in app/views/users/index.html.erb

app/views/users/new.html.slim
- provide(:title, "ユーザー登録")
h1
  | ユーザー登録
.row
  .col-md-6.col-md-offset-3
    = form_with model: @user, local: true do |f|
      = render 'shared/error_messages', object: f.object
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control', id: 'user_name'
      .form-group
        = f.label :email
        = f.email_field :email, class: 'form-control', id: 'user_email'
      .form-group
        = f.label :password
        = f.password_field :password, class: 'form-control', id: 'user_password'
      .form-group
        = f.label :password_confirmation
        = f.password_field :password_confirmation, class: 'form-control', id: 'user_password_confirmation'
      = f.submit nil, class: 'btn btn-primary'

app/views/users/show.html.slim
- provide(:title, "プロフィール")
.container
  h3.title-profile
    | プロフィール
  .row
    .col-md-4
      .user-picture-box
        = gravatar_for @user, size: 120, cl: "gravatar user-picture"
    .col-md-8
      h4.show-user-name
        = @user.name
      div
        = @user.introduction
      div
        = @user.media_url
      div
        = @user.total_goal_profit
      - if current_user == @user
        .account-edit
          = link_to "プロフィール編集", edit_user_path(@user)
  = link_to "新規キーワード登録", new_keyword_path, class: "btn btn-primary btn-lg btn-record"
  .row
    .col-md-12
      - if @user.keywords.any?
        h3
          | キーワード (
          = @user.keywords.count
          | )
        .table-responsive
          |
          table.table.table-condensed

        thead
          tr

        th
          | ID
        th
          | キーワード
        th
          | 検索Vol
        th
          | 目標順位
        th
          | 想定流入数
        th
          | 想定CVR
        th
          | 想定平均単価
        th
          | 想定報酬額
        th
          | メモ
        tbody
          - @keywords.each do |keyword|
            tr

            td
              = keyword.id
            th
              = keyword.query
            td
              = keyword.volume
            td
              = keyword.goal_rank
              | 位
            td
              = keyword.goal_pv
              | PV
            th
              = keyword.goal_cvr
              | %
            td
              = keyword.goal_price
              | 円
            td.goal_profit
              = keyword.goal_profit.to_i
              | 円
            td
              = keyword.description
            td
              = link_to edit_keyword_path(keyword.id), class: "keyword_edit", method: :get do
                i.fas.fa-pen
            td
              = link_to keyword_path(keyword.id), class: "keyword_destroy",
              -                        data: { confirm: "本当に削除しますか？" } , method: :delete do
              i.far.fa-trash-alt
      |
    = will_paginate @keywords